{% set name = "fast-pt" %}
{% set version = "3.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/JoeMcEwen/FAST-PT/archive/v{{ version }}.tar.gz
  sha256: 6b444fe05817b0f5d2d252f0868bf54f39661f41ca967a6609f1be0e995666ae

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy
    - scipy
    - matplotlib-base

test:
  imports:
    - fastpt

about:
  home: https://github.com/JoeMcEwen/FAST-PT
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: |
    FAST-PT is a code to calculate quantities in cosmological perturbation theory
    at 1-loop (including, e.g., corrections to the matter power spectrum).

extra:
  recipe-maintainers:
    - beckermr
