{% set name = "fast-pt" %}
{% set version = "4.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/fast_pt-{{ version }}.tar.gz
  sha256: 795a76dacfc47410c27f0838c5aa26b1b80b2d070ddd40ddcbe347b426ffdfed

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.17
    - scipy >=1.2
    - matplotlib-base >=3.0

test:
  imports:
    - fastpt
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/fast-pt/
  summary: FAST-PT is a code to calculate quantities in cosmological perturbation theory at 1-loop (including, e.g., corrections to the matter power spectrum).
  dev_url: https://github.com/jablazek/FAST-PT
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - beckermr
    - jablazek
    - dderienzo
